name=Sequent Microsystems 8 Relay HAT
version=1.0.0
author=Sequent Microsystems
maintainer=Sequent Microsystems <https://sequentmicrosystems.com/pages/contact-us>
sentence=Sequent Microsystems 8 Relay HAT
paragraph=Sequent Microsystems 8 Relay HAT
category=Relays
url=https://sequentmicrosystems.com/products/eight-relays-stackable-card-for-raspberry-pi
architectures=*
depends=